# coding: utf-8

"""
    FreeChat OpenAPI Definition

    https://github.com/freechat-fun/freechat

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freechat_sdk.api.app_config_for_admin_api import AppConfigForAdminApi


class TestAppConfigForAdminApi(unittest.TestCase):
    """AppConfigForAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppConfigForAdminApi()

    def tearDown(self) -> None:
        pass

    def test_get_app_config(self) -> None:
        """Test case for get_app_config

        Get Configuration
        """
        pass

    def test_get_app_config_by_version(self) -> None:
        """Test case for get_app_config_by_version

        Get Specified Version of Configuration
        """
        pass

    def test_list_app_config_names(self) -> None:
        """Test case for list_app_config_names

        List Configuration Names
        """
        pass

    def test_publish_app_config(self) -> None:
        """Test case for publish_app_config

        Publish Configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
