# coding: utf-8

"""
    FreeChat OpenAPI Definition

    https://github.com/freechat-fun/freechat

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freechat_sdk.api.app_meta_for_admin_api import AppMetaForAdminApi


class TestAppMetaForAdminApi(unittest.TestCase):
    """AppMetaForAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppMetaForAdminApi()

    def tearDown(self) -> None:
        pass

    def test_expose(self) -> None:
        """Test case for expose

        Expose DTO definitions
        """
        pass

    def test_get_app_meta(self) -> None:
        """Test case for get_app_meta

        Get Application Information
        """
        pass


if __name__ == '__main__':
    unittest.main()
