# coding: utf-8

"""
    FreeChat OpenAPI Definition

    https://github.com/freechat-fun/freechat

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freechat_sdk.models.plugin_create_dto import PluginCreateDTO

class TestPluginCreateDTO(unittest.TestCase):
    """PluginCreateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginCreateDTO:
        """Test PluginCreateDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginCreateDTO`
        """
        model = PluginCreateDTO()
        if include_optional:
            return PluginCreateDTO(
                visibility = '',
                name = '',
                manifest_format = '',
                manifest_info = '',
                api_format = '',
                api_info = '',
                provider = '',
                ext = '',
                tags = [
                    ''
                    ],
                ai_models = [
                    ''
                    ]
            )
        else:
            return PluginCreateDTO(
                name = '',
        )
        """

    def testPluginCreateDTO(self):
        """Test PluginCreateDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
