version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VER}
    ports: 
      - '${MYSQL_HOST_PORT}:${MYSQL_PORT}'
    container_name: '${MYSQL_NAME}'
    volumes:
      - ${MYSQL_DATA}/conf.d:/etc/mysql/conf.d
      - ${MYSQL_DATA}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    network_mode: bridge

  redis:
    image: redis:${REDIS_VER}
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_PORT}'
    container_name: '${REDIS_NAME}'
    command: [ 'redis-server', '--appendonly', 'yes', '--requirepass', '${REDIS_PASSWORD}' ]
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    network_mode: bridge
