/*
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fun.freechat.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fun.freechat.client.model.AiModelInfoDTO;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentSummaryDTO
 */
public class AgentSummaryDTOTest {
    private final AgentSummaryDTO model = new AgentSummaryDTO();

    /**
     * Model tests for AgentSummaryDTO
     */
    @Test
    public void testAgentSummaryDTO() {
        // TODO: test AgentSummaryDTO
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'agentUid'
     */
    @Test
    public void agentUidTest() {
        // TODO: test agentUid
    }

    /**
     * Test the property 'gmtCreate'
     */
    @Test
    public void gmtCreateTest() {
        // TODO: test gmtCreate
    }

    /**
     * Test the property 'gmtModified'
     */
    @Test
    public void gmtModifiedTest() {
        // TODO: test gmtModified
    }

    /**
     * Test the property 'parentUid'
     */
    @Test
    public void parentUidTest() {
        // TODO: test parentUid
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'aiModels'
     */
    @Test
    public void aiModelsTest() {
        // TODO: test aiModels
    }

}
