/*
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fun.freechat.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppMetaDTO
 */
public class AppMetaDTOTest {
    private final AppMetaDTO model = new AppMetaDTO();

    /**
     * Model tests for AppMetaDTO
     */
    @Test
    public void testAppMetaDTO() {
        // TODO: test AppMetaDTO
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'buildTimestamp'
     */
    @Test
    public void buildTimestampTest() {
        // TODO: test buildTimestamp
    }

    /**
     * Test the property 'buildNumber'
     */
    @Test
    public void buildNumberTest() {
        // TODO: test buildNumber
    }

    /**
     * Test the property 'commitUrl'
     */
    @Test
    public void commitUrlTest() {
        // TODO: test commitUrl
    }

    /**
     * Test the property 'releaseNoteUrl'
     */
    @Test
    public void releaseNoteUrlTest() {
        // TODO: test releaseNoteUrl
    }

    /**
     * Test the property 'runningEnv'
     */
    @Test
    public void runningEnvTest() {
        // TODO: test runningEnv
    }

}
