/*
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fun.freechat.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fun.freechat.client.model.AiModelInfoDTO;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PluginSummaryStatsDTO
 */
public class PluginSummaryStatsDTOTest {
    private final PluginSummaryStatsDTO model = new PluginSummaryStatsDTO();

    /**
     * Model tests for PluginSummaryStatsDTO
     */
    @Test
    public void testPluginSummaryStatsDTO() {
        // TODO: test PluginSummaryStatsDTO
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'pluginId'
     */
    @Test
    public void pluginIdTest() {
        // TODO: test pluginId
    }

    /**
     * Test the property 'pluginUid'
     */
    @Test
    public void pluginUidTest() {
        // TODO: test pluginUid
    }

    /**
     * Test the property 'gmtCreate'
     */
    @Test
    public void gmtCreateTest() {
        // TODO: test gmtCreate
    }

    /**
     * Test the property 'gmtModified'
     */
    @Test
    public void gmtModifiedTest() {
        // TODO: test gmtModified
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'manifestFormat'
     */
    @Test
    public void manifestFormatTest() {
        // TODO: test manifestFormat
    }

    /**
     * Test the property 'apiFormat'
     */
    @Test
    public void apiFormatTest() {
        // TODO: test apiFormat
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'aiModels'
     */
    @Test
    public void aiModelsTest() {
        // TODO: test aiModels
    }

    /**
     * Test the property 'viewCount'
     */
    @Test
    public void viewCountTest() {
        // TODO: test viewCount
    }

    /**
     * Test the property 'referCount'
     */
    @Test
    public void referCountTest() {
        // TODO: test referCount
    }

    /**
     * Test the property 'recommendCount'
     */
    @Test
    public void recommendCountTest() {
        // TODO: test recommendCount
    }

    /**
     * Test the property 'scoreCount'
     */
    @Test
    public void scoreCountTest() {
        // TODO: test scoreCount
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

}
