/*
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fun.freechat.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PluginQueryWhere
 */
public class PluginQueryWhereTest {
    private final PluginQueryWhere model = new PluginQueryWhere();

    /**
     * Model tests for PluginQueryWhere
     */
    @Test
    public void testPluginQueryWhere() {
        // TODO: test PluginQueryWhere
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'manifestFormat'
     */
    @Test
    public void manifestFormatTest() {
        // TODO: test manifestFormat
    }

    /**
     * Test the property 'apiFormat'
     */
    @Test
    public void apiFormatTest() {
        // TODO: test apiFormat
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'tagsOp'
     */
    @Test
    public void tagsOpTest() {
        // TODO: test tagsOp
    }

    /**
     * Test the property 'aiModels'
     */
    @Test
    public void aiModelsTest() {
        // TODO: test aiModels
    }

    /**
     * Test the property 'aiModelsOp'
     */
    @Test
    public void aiModelsOpTest() {
        // TODO: test aiModelsOp
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
