/**
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChatPromptContentDTO from './ChatPromptContentDTO';

/**
 * The PromptUpdateDTO model module.
 * @module model/PromptUpdateDTO
 * @version 0.1.0
 */
class PromptUpdateDTO {
    /**
     * Constructs a new <code>PromptUpdateDTO</code>.
     * Request data for updating prompt information
     * @alias module:model/PromptUpdateDTO
     * @param name {String} Prompt name
     */
    constructor(name) { 
        
        PromptUpdateDTO.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PromptUpdateDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PromptUpdateDTO} obj Optional instance to populate.
     * @return {module:model/PromptUpdateDTO} The populated <code>PromptUpdateDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromptUpdateDTO();

            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('chatTemplate')) {
                obj['chatTemplate'] = ChatPromptContentDTO.constructFromObject(data['chatTemplate']);
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('lang')) {
                obj['lang'] = ApiClient.convertToType(data['lang'], 'String');
            }
            if (data.hasOwnProperty('example')) {
                obj['example'] = ApiClient.convertToType(data['example'], 'String');
            }
            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], 'String');
            }
            if (data.hasOwnProperty('ext')) {
                obj['ext'] = ApiClient.convertToType(data['ext'], 'String');
            }
            if (data.hasOwnProperty('draft')) {
                obj['draft'] = ApiClient.convertToType(data['draft'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('aiModels')) {
                obj['aiModels'] = ApiClient.convertToType(data['aiModels'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PromptUpdateDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PromptUpdateDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PromptUpdateDTO.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['visibility'] && !(typeof data['visibility'] === 'string' || data['visibility'] instanceof String)) {
            throw new Error("Expected the field `visibility` to be a primitive type in the JSON string but got " + data['visibility']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['template'] && !(typeof data['template'] === 'string' || data['template'] instanceof String)) {
            throw new Error("Expected the field `template` to be a primitive type in the JSON string but got " + data['template']);
        }
        // validate the optional field `chatTemplate`
        if (data['chatTemplate']) { // data not null
          ChatPromptContentDTO.validateJSON(data['chatTemplate']);
        }
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }
        // ensure the json data is a string
        if (data['lang'] && !(typeof data['lang'] === 'string' || data['lang'] instanceof String)) {
            throw new Error("Expected the field `lang` to be a primitive type in the JSON string but got " + data['lang']);
        }
        // ensure the json data is a string
        if (data['example'] && !(typeof data['example'] === 'string' || data['example'] instanceof String)) {
            throw new Error("Expected the field `example` to be a primitive type in the JSON string but got " + data['example']);
        }
        // ensure the json data is a string
        if (data['inputs'] && !(typeof data['inputs'] === 'string' || data['inputs'] instanceof String)) {
            throw new Error("Expected the field `inputs` to be a primitive type in the JSON string but got " + data['inputs']);
        }
        // ensure the json data is a string
        if (data['ext'] && !(typeof data['ext'] === 'string' || data['ext'] instanceof String)) {
            throw new Error("Expected the field `ext` to be a primitive type in the JSON string but got " + data['ext']);
        }
        // ensure the json data is a string
        if (data['draft'] && !(typeof data['draft'] === 'string' || data['draft'] instanceof String)) {
            throw new Error("Expected the field `draft` to be a primitive type in the JSON string but got " + data['draft']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['aiModels'])) {
            throw new Error("Expected the field `aiModels` to be an array in the JSON data but got " + data['aiModels']);
        }

        return true;
    }


}

PromptUpdateDTO.RequiredProperties = ["name"];

/**
 * Referenced prompt
 * @member {String} parentId
 */
PromptUpdateDTO.prototype['parentId'] = undefined;

/**
 * Visibility: private (default), public, public_org, hidden
 * @member {String} visibility
 */
PromptUpdateDTO.prototype['visibility'] = undefined;

/**
 * Prompt name
 * @member {String} name
 */
PromptUpdateDTO.prototype['name'] = undefined;

/**
 * Prompt description
 * @member {String} description
 */
PromptUpdateDTO.prototype['description'] = undefined;

/**
 * Prompt text template content, choose one from template and chatTemplate field, priority: template > chatTemplate
 * @member {String} template
 */
PromptUpdateDTO.prototype['template'] = undefined;

/**
 * @member {module:model/ChatPromptContentDTO} chatTemplate
 */
PromptUpdateDTO.prototype['chatTemplate'] = undefined;

/**
 * Prompt format: mustache (default) | f_string
 * @member {String} format
 */
PromptUpdateDTO.prototype['format'] = undefined;

/**
 * Prompt language: en (default) | zh_CN | ...
 * @member {String} lang
 */
PromptUpdateDTO.prototype['lang'] = undefined;

/**
 * Prompt example
 * @member {String} example
 */
PromptUpdateDTO.prototype['example'] = undefined;

/**
 * Prompt parameters, JSON format
 * @member {String} inputs
 */
PromptUpdateDTO.prototype['inputs'] = undefined;

/**
 * Additional information, JSON format
 * @member {String} ext
 */
PromptUpdateDTO.prototype['ext'] = undefined;

/**
 * Draft content
 * @member {String} draft
 */
PromptUpdateDTO.prototype['draft'] = undefined;

/**
 * Tag set
 * @member {Array.<String>} tags
 */
PromptUpdateDTO.prototype['tags'] = undefined;

/**
 * Supported model set, empty means no model limit
 * @member {Array.<String>} aiModels
 */
PromptUpdateDTO.prototype['aiModels'] = undefined;






export default PromptUpdateDTO;

