app:
  homeUrl: http://localhost
  logging:
    home: ${APP_HOME}/logs
    level: info
  avatar:
    maxSize: 1048576  # 1M
    maxCount: 10
  document:
    maxSize: 10485760  # 10M
    maxCount: 5
  picture:
    maxSize: 2097152  # 2M
    maxCount: 10
  video:
    maxSize: 10485760  # 10M
    maxCount: 5
  voice:
    maxSize: 1048576  # 1M
    maxCount: 1
  web:
    version: ''
auth:
  aes:
    key: 6034a30c93dd4342a3e2d1973bc13ee5
  login:
    uri: /w/login
    processingUri: /login
    oauth2:
      failureUri: /login/oauth2/failure
      successUri: /login/oauth2/success
    portal:
      failureUri: /login/portal/failure
      successUri: /login/portal/success
  logout:
    uri: /logout
    successUri: /
  rememberMe:
    alwaysRemember: true
  role:
    adminUri: /admin/**,/api/v2/admin/**
    bizAdminUri: /api/v2/biz/admin/**
    apiUri: /api/**
    privateUri: /private/**
    publicUri: /,/undefined,/error,/w,/w/docs,/w/privacy-policy,/s/**,/public/**,/api/v2/public/**,/assets/**,/css/**,/js/**,/img/**,/logo/**,/favicon.ico,/baidu*.html
  token:
    limits: 5
    prefix: fc-
  impersonate:
    headerName: X-FC-IMPERSONATE
    autoRegister: true
  aiApiKey:
    limits: 3
chat:
  memory:
    maxMessageSize: 1000
    maxMessageWindowSize: 500
    minMessageWindowSize: 5
    defaultMessageWindowSize: 50
    maxLongTermMemoryWindowSize: 30
    minLongTermMemoryWindowSize: 0
    defaultLongTermMemoryWindowSize: 5
  rag:
    maxMaxSegmentSize: 1000
    minMaxSegmentSize: 0
    defaultMaxSegmentSize: 300
    maxMaxOverlapSize: 100
    minMaxOverlapSize: 0
    defaultMaxOverlapSize: 30
    maxResults: 2
    minScore: 0.3
embedding:
  milvus:
    retrieveEmbeddingsOnSearch: false
    url: http://localhost:19530
tts:
  baseUrl: http://localhost:5002
  format: mp3
  timeout: 180000
configmap:
  workdir: ${APP_HOME}/config.run
disk:
  workdir: ${APP_HOME}/data
redis:
  mode: single
  datasource:
    url: redis://localhost:6379
    password: hello1234
    timeout: 10000
management:
  endpoints:
    web:
      exposure:
        include: '*'
      basePath: /public/actuator
  endpoint:
    health:
      db:
        enabled: true
      diskSpace:
        enabled: true
      probes:
        enabled: true
      redis:
        enabled: true
      showDetails: always
  server:
    port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freechat?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hello1234
  security:
    oauth2:
      client:
        provider:
          aliyun:
            authorizationUri: https://signin.aliyun.com/oauth2/v1/auth
            issuerUri: https://oauth.aliyun.com
            jwkSetUri: https://oauth.aliyun.com/v1/keys
            tokenUri: https://oauth.aliyun.com/v1/token
            userInfoUri: https://oauth.aliyun.com/v1/userinfo
            userNameAttribute: sub
        registration:
          github:
            clientId: 'fakeId'
            clientSecret: 'fakeSecret'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  task:
    taskExecution:
      threadNamePrefix: default-task-
      pool:
        coreSize: 2
        maxSize: 16
        keepAlive: 90s
        queueCapacity: 64
        allowCoreThreadTimeout: true
      shutdown:
        awaitTermination: true
        awaitTerminationPeriod: 60s
    eventExecution:
      threadNamePrefix: event-task-
      pool:
        coreSize: 1
        maxSize: 4
        keepAlive: 60s
        queueCapacity: 1024
        allowCoreThreadTimeout: true
      shutdown:
        awaitTermination: true
        awaitTerminationPeriod: 60s
    ragExecution:
      threadNamePrefix: rag-task-
      pool:
        coreSize: 1
        maxSize: 2
        keepAlive: 60s
        queueCapacity: 128
        allowCoreThreadTimeout: true
      shutdown:
        awaitTermination: true
        awaitTerminationPeriod: 60s
springdoc:
  apiDocs:
    path: /public/openapi/v3/api-docs
  swaggerUi:
    path: /public/docs/api/swagger-ui
  paths: /api/**
  packagesToScan: fun.freechat.api
  defaultProducesMediaType: application/json
  groupConfigs:
    - group: g-all
      displayName: All
      pathsToMatch: /api/**
    - group: g-admin
      displayName: Admin
      pathsToMatch: /api/v2/admin/**
    - group: g-biz-admin
      displayName: BizAdmin
      pathsToMatch: /api/v2/biz/admin/**
    - group: g-account
      displayName: Account
      pathsToMatch: /api/v2/account/**
    - group: g-prompt
      displayName: Prompt
      pathsToMatch: /api/v2/prompt/**
    - group: g-plugin
      displayName: Plugin
      pathsToMatch: /api/v2/plugin/**
    - group: g-agent
      displayName: Agent
      pathsToMatch: /api/v2/agent/**
    - group: g-character
      displayName: Character
      pathsToMatch: /api/v2/character/**
    - group: g-chat
      displayName: Chat
      pathsToMatch: /api/v2/chat/**
    - group: g-rag
      displayName: RAG
      pathsToMatch: /api/v2/rag/**
    - group: g-organization
      displayName: Organization
      pathsToMatch: /api/v2/org/**
    - group: g-ai
      displayName: AI
      pathsToMatch: /api/v2/ai/**
    - group: g-stats
      displayName: Stats
      pathsToMatch: /api/v2/stats/**,/api/v2/score/**
perf:
  trace:
    excludeUri: /public/check/**,/favicon.ico,/assets/**,/css/**,/js/**,/img/**,/logo/**,/error
