# 2 seconds cache
# NOTE: Because the cache is often invalidated,
# it is recommended to set "sync" to true to prevent cache breakdown as
# @Cacheable(cacheNames = "freechatShortPeriodCache", sync = true...)
freechatShortPeriodCache:
  ttl: 2000
  maxIdleTime: 1000

# 5 minutes cache
freechatMiddlePeriodCache:
  ttl: 300000
  maxIdleTime: 150000

# 1 hour cache
freechatLongPeriodCache:
  ttl: 3600000
  maxIdleTime: 1800000
