package fun.freechat.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

@Schema(description = "Qwen series model parameters")
@Data
@EqualsAndHashCode(callSuper = true)
public class QwenParamDTO extends AiModelParamDTO{
    @Schema(description = "Probability threshold of the nucleus sampling method in the generation process, for example, when the value is 0.8, only the smallest set of most likely tokens whose probabilities add up to 0.8 or more is retained as the candidate set. The value range is (0, 1.0), the larger the value, the higher the randomness of the generation; the smaller the value, the higher the certainty of the generation.")
    private Double topP;
    @Schema(description = "The size of the sampling candidate set during generation. For example, when the value is 50, only the top 50 tokens with the highest scores in a single generation are included in the random sampling candidate set. The larger the value, the higher the randomness of the generation; the smaller the value, the higher the certainty of the generation. The default value is 0, which means that the top_k strategy is not enabled, and only the top_p strategy is effective.")
    private Integer topK;
    @Schema(description = "The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length.")
    private Integer maxTokens;
    @Schema(description = "Whether to use a search engine for data enhancement.")
    private Boolean enableSearch;
    @Schema(description = "The random number seed used when generating, the user controls the randomness of the content generated by the model. seed supports unsigned 64-bit integers, with a default value of 1234. When using seed, the model will try its best to generate the same or similar results, but there is currently no guarantee that the results will be exactly the same every time.")
    private Integer seed;
    @Schema(description = "Used to control the repeatability when generating models. Increasing repetition_penalty can reduce the duplication of model generation. 1.0 means no punishment.")
    private Float repetitionPenalty;
    @Schema(description = "Used to adjust the degree of randomness from sampling in the generated model, the value range is [0, 2), a temperature of 0 will always produce the same output. The higher the temperature, the greater the randomness.")
    private Float temperature;
    @Schema(description = "A collection of stop words that controls the API from generating more tokens.")
    private List<String> stop;
}
