{
 "title": "Freechat Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        | pattern `<_> [<_>] <_> <_> - <_>|<username>|<_>`\n        | keep username [$__range]\n    )\n)"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "Number of Conversations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\"}\n    |= \"|/api/v1/chat/send/stream\" [$__range]\n)"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "New Characters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\"}\n    |= \"|/api/v1/character|\" [$__range]\n)"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "Character Activity Ranking",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by (name) (\n        count_over_time (\n            {app=\"freechat-main\", level=\"PERF\", class=\"ChatApi\", method=\"firstPackageReceived\"}\n            | pattern `<_>|\"<name>\",<_>` [$__range]\n        )\n    )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Count Ranking",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by (api) (\n        count_over_time (\n            {app=\"freechat-main\", level=\"ACCESS\"}\n            |= \"|/api\"\n            | label_format api=`{{.method}} {{.path}}` [$__range]\n        )\n    )\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request Latency Ranking",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    avg_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        |= \"|/api\"\n        | pattern \"<_>|<path>::<method>|<_>|<rt>|<_>\"\n        | label_format api=`{{.method}} {{.path}}`\n        | unwrap rt [$__range]\n    ) by (api)\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum (\n    rate (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        |= \"|/api\" [1m]\n    )\n)"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\"}\n    |= \"|/api\"\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "avg(ms)"
    },
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\"}\n    |= \"|/api\"\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "max(ms)"
    }
   ]
  },
  {
   "title": "Response Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (code) (\n    rate (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        |= \"|/api\"\n        | pattern \"<_>|<_>::<_>|<_>|<_>|<_>|<http_code>|<_>\"\n        | label_format code=`{{ regexReplaceAll \"(\\\\d{1})\\\\d*\" .http_code \"${1}xx\" }}`\n        | keep code [1m]\n    )\n)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Success/Bad Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (code) (\n    rate (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        |= \"|/api\"\n        | pattern \"<_>|<_>::<_>|<_>|<_>|<_>|<http_code>|<_>\"\n        | label_format code=`{{ regexReplaceAll \"(\\\\d{1})\\\\d*\" .http_code \"${1}xx\" }}`\n        | keep code [1m]\n    )\n)"
    },
    {
     "expr": "sum (\n    rate (\n        {app=\"freechat-main\", level=\"ACCESS\"}\n        |= \"|/api\" [1m]\n    )\n)"
    }
   ]
  },
  {
   "title": "First Package Latency of Chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  {
   "title": "Last Package Latency of Chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"lastPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  {
   "title": "Retrieve Knowledge Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  {
   "title": "Retrieve Memory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Avg First Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max First Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)"
    }
   ]
  },
  {
   "title": "Avg Last Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"lastPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Last Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Retrieve Knowledge Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Retrieve Knowledge Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Retrieve Memory Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Retrieve Memory Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}