{
 "title": "Freechat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=\"/\"}\n        | pattern `<_> [<_>] <_> <_> - <_>|<username>|<_>`\n        | keep username [$__range]\n    )\n)"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "Activate Visits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=\"/\"} [$__interval]\n    )\n) by () or vector(0)"
    }
   ]
  },
  {
   "title": "Number of Conversations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api/v1/chat/send/stream.*\", method=\"POST\"} [$__interval]\n    )\n) by () or vector(0)"
    }
   ]
  },
  {
   "title": "New Characters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=\"/api/v1/character\", method=\"POST\"} [$__interval]\n    )\n) by () or vector(0)"
    }
   ]
  },
  {
   "title": "Character Activity Ranking",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by (name) (\n        count_over_time (\n            {app=\"freechat-main\", level=\"PERF\", class=\"ChatApi\", method=\"firstPackageReceived\"}\n            | pattern `<_>|\"<name>\",<_>` [$__range]\n        )\n    )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n    | keep http_code [$__range]\n)",
     "legendFormat": "{{http_code}}"
    }
   ]
  },
  {
   "title": "Response Status Trends",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum (\n    rate (\n        {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n        | label_format code=`{{ regexReplaceAll \"(\\\\d{1})\\\\d*\" .http_code \"${1}xx\" }}`\n        | keep code [1m]\n    ) * 60\n) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"} [$__range]\n    )\n) by () or vector(0)",
     "legendFormat": "Requests"
    },
    { "expression": "C", "reducer": "last", "settings": { "mode": "replaceNN", "replaceWithValue": 100 }, "type": "reduce" }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\", status!=\"F\"} [1m]\n        )\n    ) by () or vector(0)\n) * 100 / \n(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"} [1m]\n        )\n    ) by () or vector(0)\n)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"} [1m]\n        )\n    ) by () or vector(0)\n) * 60",
     "legendFormat": "qpm"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [$__interval]\n) by () or vector(0)",
     "legendFormat": "avg(ms)"
    },
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [$__interval]\n) by () or vector(0)",
     "legendFormat": "max(ms)"
    }
   ]
  },
  {
   "title": "Chat Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api/v1/chat/send/stream.*\", method=\"POST\"} [$__range]\n    )\n) by () or vector(0)",
     "legendFormat": "Requests"
    },
    { "expression": "C", "reducer": "last", "settings": { "mode": "replaceNN", "replaceWithValue": 100 }, "type": "reduce" }
   ]
  },
  {
   "title": "Chat Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api/v1/chat/send/stream.*\", method=\"POST\", status!=\"F\"} [1m]\n        )\n    ) by () or vector(0)\n) * 100 / \n(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api/v1/chat/send/stream.*\", method=\"POST\"} [1m]\n        )\n    ) by () or vector(0)\n)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Chat Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api/v1/chat/send/stream.*\", method=\"POST\"} [1m]\n        )\n    ) by () or vector(0)\n) * 60",
     "legendFormat": "qpm"
    }
   ]
  },
  {
   "title": "First Package Latency of Chat",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "avg(ms)"
    },
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "max(ms)"
    }
   ]
  },
  {
   "title": "Last Package Latency of Chat",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"lastPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "avg(ms)"
    },
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"lastPackageReceived\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "max(ms)"
    }
   ]
  },
  {
   "title": "Retrieve Knowledge Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"} [$__range]\n    )\n) by () or vector(0)",
     "legendFormat": "Requests"
    },
    { "expression": "C", "reducer": "last", "settings": { "mode": "replaceNN", "replaceWithValue": 100 }, "type": "reduce" }
   ]
  },
  {
   "title": "Retrieve Knowledge Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\", status!=\"F\"} [1m]\n        )\n    ) by () or vector(0)\n) * 100 / \n(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"} [1m]\n        )\n    ) by () or vector(0)\n)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Retrieve Knowledge Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"} [1m]\n        )\n    ) by () or vector(0)\n) * 60",
     "legendFormat": "qpm"
    }
   ]
  },
  {
   "title": "Retrieve Knowledge Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  {
   "title": "Retrieve Memory Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    count_over_time (\n        {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"} [$__range]\n    )\n) by () or vector(0)",
     "legendFormat": "Requests"
    },
    { "expression": "C", "reducer": "last", "settings": { "mode": "replaceNN", "replaceWithValue": 100 }, "type": "reduce" }
   ]
  },
  {
   "title": "Retrieve Memory Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\", status!=\"F\"} [1m]\n        )\n    ) by () or vector(0)\n) * 100 / \n(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"} [1m]\n        )\n    ) by () or vector(0)\n)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Retrieve Memory Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "(\n    sum (\n        rate (\n            {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"} [1m]\n        )\n    ) by () or vector(0)\n) * 60",
     "legendFormat": "qpm"
    }
   ]
  },
  {
   "title": "Retrieve Memory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n    | unwrap rt [1m]\n) by ()",
     "legendFormat": "rt(ms)"
    }
   ]
  },
  {
   "title": "Request Count Ranking",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by (api) (\n        count_over_time (\n            {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n            | label_format api=`{{.method}} {{.path}}` [$__range]\n        )\n    )\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request Latency Ranking",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, \n    avg_over_time (\n        {app=\"freechat-main\", level=\"ACCESS\", path=~\"/api.*\"}\n        | pattern \"<_>|<_>::<_>|<_>|<rt>|<_>\"\n        | label_format api=`{{.method}} {{.path}}`\n        | unwrap rt [$__range]\n    ) by (api)\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Avg First Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max First Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Last Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"lastPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Last Package Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"firstPackageReceived\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Retrieve Knowledge Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Retrieve Knowledge Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveKnowledge\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Retrieve Memory Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "avg_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Retrieve Memory Latency of Characters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "max_over_time (\n    {app=\"freechat-main\", level=\"PERF\", method=\"retrieveLongTermMemory\"}\n    | pattern `<_>|<_>::<_>|<_>|<rt>|\"<name>\",<_>`\n    | unwrap rt [1m]\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}