{
 "title": "kube-state-metrics-v2-修正版",
 "description": "Summary metrics about kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics);\r\n\r\nSame as the other two, the only difference is that this is a corrected version.\r\nYou only need to configure auto-discovery to complete the dashboard\r\nPlease install kube-state-metrics and configure the namespace\r\n和其他两个一样，唯一不同的是，这是一个修正版本。\r\n你只需要配置自动发现就可以完成dashboard\r\n请安装kube-state-metrics，并且配置名称空间",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "datasource", "query": "${VAR_DATASOURCE}" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\",cluster=~\"$cluster\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Node NotReady",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}==1",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Pressure",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"DiskPressure\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      }
     ]
    },
    {
     "title": "node number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods restart in 30m",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m])>1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_status_reason{cluster=~\"$cluster\",namespace=~\"$namespace\", reason=\"Evicted\"}==1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" ,cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "hpa",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=~\"$cluster\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "pvc is bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}