/**
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Application metadata
*/
export class AppMetaDTO {
    /**
    * Application name
    */
    'name'?: string;
    /**
    * Application version
    */
    'version'?: string;
    /**
    * Build time
    */
    'buildTimestamp'?: string;
    /**
    * Build number
    */
    'buildNumber'?: string;
    /**
    * Commit URL
    */
    'commitUrl'?: string;
    /**
    * Release notes
    */
    'releaseNoteUrl'?: string;
    /**
    * Running environment
    */
    'runningEnv'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildTimestamp",
            "baseName": "buildTimestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildNumber",
            "baseName": "buildNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "commitUrl",
            "baseName": "commitUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseNoteUrl",
            "baseName": "releaseNoteUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "runningEnv",
            "baseName": "runningEnv",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppMetaDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

