/**
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Qwen series model parameters
*/
export class QwenParamDTO {
    /**
    * API-KEY, higher priority than apiKeyName. Either apiKey or apiKeyName must be specified.
    */
    'apiKey'?: string;
    /**
    * API-KEY name
    */
    'apiKeyName'?: string;
    /**
    * Model identifier
    */
    'modelId': string;
    /**
    * Probability threshold of the nucleus sampling method in the generation process, for example, when the value is 0.8, only the smallest set of most likely tokens whose probabilities add up to 0.8 or more is retained as the candidate set. The value range is (0, 1.0), the larger the value, the higher the randomness of the generation; the smaller the value, the higher the certainty of the generation. The default value is 0.5.
    */
    'topP'?: number;
    /**
    * The size of the sampling candidate set during generation. For example, when the value is 50, only the top 50 tokens with the highest scores in a single generation are included in the random sampling candidate set. The larger the value, the higher the randomness of the generation; the smaller the value, the higher the certainty of the generation. The default value is 0, which means that the top_k strategy is not enabled, and only the top_p strategy is effective. The default value is 0.
    */
    'topK'?: number;
    /**
    * Whether to use a search engine for data enhancement. Default is false.
    */
    'enableSearch'?: boolean;
    /**
    * During generation, the seed of the random number, used to control the randomness of the model generation. If the same seed is used, the results of each run will be the same; when you need to reproduce the results of the model, you can use the same seed. The default value is 1234.
    */
    'seed'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKeyName",
            "baseName": "apiKeyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "modelId",
            "type": "string",
            "format": ""
        },
        {
            "name": "topP",
            "baseName": "topP",
            "type": "number",
            "format": "double"
        },
        {
            "name": "topK",
            "baseName": "topK",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "enableSearch",
            "baseName": "enableSearch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "seed",
            "baseName": "seed",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return QwenParamDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

