{{- if (index .Values "grafana-loki" "deployment" "enabled") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.fullname" . }}-promtail-configuration
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
data:
  promtail.yaml: |-
    server:
      log_level: {{ index .Values "grafana-loki" "promtail" "logLevel" }}
      http_listen_port: {{ index .Values "grafana-loki" "promtail" "containerPorts" "http" }}
      grpc_listen_port: {{ index .Values "grafana-loki" "promtail" "containerPorts" "grpc" }}
      
    clients:
      - url: http://{{ template "helpers.fullname" . }}-grafana-loki-gateway:{{ index .Values "grafana-loki" "gateway" "service" "ports" "http" }}/loki/api/v1/push
        {{- if (index .Values "grafana-loki" "gateway" "auth" "enabled") }}
        basic_auth:
          # The username to use for basic auth
          username: {{ index .Values "grafana-loki" "gateway" "auth" "username" }}
          password_file: /bitnami/promtail/conf/secrets/password
        {{- end }}
    positions:
      filename: /run/promtail/positions.yaml
    
    scrape_configs:
      - job_name: {{ template "helpers.fullname" . }}-main-logs
        static_configs:
          - targets:
              - localhost 
            labels:
              app: {{ template "helpers.fullname" . }}-main
              component: main
              container: main
              namespace: {{ template "helpers.namespace" . }}
              job: {{ template "helpers.namespace" . }}/{{ template "helpers.fullname" . }}-main
              __path__: /home/{{ .Values.systemAccount }}/{{ include "helpers.name" . }}/logs/common-*.log*
        pipeline_stages:
          - multiline:
              firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}'
              max_wait_time: 3s
          - regex: 
              expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[[^\]]+\] (?P<level>TRACE|DEBUG|INFO|WARN|ERROR|FATAL|PERF|ACCESS) +\S+ - (?s:.*)$'
          - labels:
              level:
          - match:
              selector: '{level="PERF"}'
              stages:
                - regex:
                    expression: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \[[^\]]+\] PERF  \S+ - [^|]*\|[^|]*\|(?P<class>[^|]*)::(?P<method>[^|]*)\|(?P<status>[^|]*)\|(?s:.*)$'
                - labels:
                    class:
                    method:
                    status:
                - template:
                    source: 'api'
                    template: '{{ "{{" }}.class{{ "}}" }}::{{ "{{" }}.method{{ "}}" }}'
          - match:
              selector: '{level="ACCESS"}'
              stages:
                - regex:
                    expression: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \[[^\]]+\] ACCESS \S+ - [^|]*\|[^|]*\|(?P<path>[^|]*)::(?P<method>[^|]*)\|(?P<status>[^|]*)\|[^|]*\|[^|]*\|(?P<http_code>[^|]*)\|(?s:.*)$'
                - labels:
                    path:
                    method:
                    status:
                    http_code:
                - template:
                    source: 'api'
                    template: '{{ "{{" }}.method{{ "}}" }} {{ "{{" }}.path{{ "}}" }}'
          - timestamp:
              source: timestamp
              format: '2006-01-02 15:04:05.000'
{{- end }}