{{- if .Values.grafana.deployment.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}-grafana-configs
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.prometheus.deployment.enabled }}
  prometheus.ini: {{ include "prometheus.ini" . | b64enc | quote }}
  {{- end }}
{{- end }}