{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  accessModes: {{ default "[ReadWriteOnce]" .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ default "8Gi" .Values.persistence.storage }}
  {{- include "helpers.storageClass" . | nindent 2 }}
  volumeMode: Filesystem
{{- end }}