{{- if and .Values.serviceAccount.create (or .Values.deployment.backend.enabled .Values.deployment.frontend.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.serviceAccountName" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
