{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}-spring-properties
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
type: Opaque
data:
  application-online.yml: {{ include "application-online.yml" . | b64enc | quote }}
{{- end }}