{{- if .Values.cert.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "helpers.name" . }}-letsencrypt-http01
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- if .Values.cert.email }}
    email: {{ .Values.cert.email }}
    {{- end }}
    privateKeySecretRef:
      name: {{ include "helpers.name" . }}-letsencrypt-http01-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
{{- end }}