/**
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.freechat-sdk);
  }
}(this, function(expect, freechat-sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new freechat-sdk.CharacterSummaryStatsDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CharacterSummaryStatsDTO', function() {
    it('should create an instance of CharacterSummaryStatsDTO', function() {
      // uncomment below and update the code to test CharacterSummaryStatsDTO
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be.a(freechat-sdk.CharacterSummaryStatsDTO);
    });

    it('should have the property requestId (base name: "requestId")', function() {
      // uncomment below and update the code to test the property requestId
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property characterId (base name: "characterId")', function() {
      // uncomment below and update the code to test the property characterId
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property gmtCreate (base name: "gmtCreate")', function() {
      // uncomment below and update the code to test the property gmtCreate
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property gmtModified (base name: "gmtModified")', function() {
      // uncomment below and update the code to test the property gmtModified
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property avatar (base name: "avatar")', function() {
      // uncomment below and update the code to test the property avatar
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property picture (base name: "picture")', function() {
      // uncomment below and update the code to test the property picture
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property lang (base name: "lang")', function() {
      // uncomment below and update the code to test the property lang
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property viewCount (base name: "viewCount")', function() {
      // uncomment below and update the code to test the property viewCount
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property referCount (base name: "referCount")', function() {
      // uncomment below and update the code to test the property referCount
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property recommendCount (base name: "recommendCount")', function() {
      // uncomment below and update the code to test the property recommendCount
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property scoreCount (base name: "scoreCount")', function() {
      // uncomment below and update the code to test the property scoreCount
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new freechat-sdk.CharacterSummaryStatsDTO();
      //expect(instance).to.be();
    });

  });

}));
