/**
 * FreeChat OpenAPI Definition
 * https://github.com/freechat-fun/freechat
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.freechat-sdk);
  }
}(this, function(expect, freechat-sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new freechat-sdk.ChatCreateDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatCreateDTO', function() {
    it('should create an instance of ChatCreateDTO', function() {
      // uncomment below and update the code to test ChatCreateDTO
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be.a(freechat-sdk.ChatCreateDTO);
    });

    it('should have the property userNickname (base name: "userNickname")', function() {
      // uncomment below and update the code to test the property userNickname
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be();
    });

    it('should have the property userProfile (base name: "userProfile")', function() {
      // uncomment below and update the code to test the property userProfile
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be();
    });

    it('should have the property characterNickname (base name: "characterNickname")', function() {
      // uncomment below and update the code to test the property characterNickname
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be();
    });

    it('should have the property backendId (base name: "backendId")', function() {
      // uncomment below and update the code to test the property backendId
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be();
    });

    it('should have the property ext (base name: "ext")', function() {
      // uncomment below and update the code to test the property ext
      //var instance = new freechat-sdk.ChatCreateDTO();
      //expect(instance).to.be();
    });

  });

}));
