services:
  mysql:
    image: mysql:${MYSQL_TAG}
    ports: 
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    container_name: ${MYSQL_NAME}
    volumes:
      - ${MYSQL_VOLUME}/conf.d:/etc/mysql/conf.d
      - ${MYSQL_VOLUME}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${MYSQL_VOLUME}/data:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 20s
      retries: 3

  redis:
    image: redis:${REDIS_TAG}
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "hello1234"]
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    container_name: ${REDIS_NAME}
    volumes:
      - ${REDIS_VOLUME}:/bitnami/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:${MILVUS_TAG}
    ports:
      - ${MILVUS_HOST_PORT}:${MILVUS_PORT}
      - ${MILVUS_CONTROL_HOST_PORT}:${MILVUS_CONTROL_PORT}
    container_name: ${MILVUS_NAME}
    volumes:
      - ${MILVUS_VOLUME}:/var/lib/milvus
    environment:
      - COMMON_STORAGETYPE=local
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/var/lib/milvus/configs/embedEtcd.yaml
    entrypoint: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
#    healthcheck:
#      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:${MILVUS_CONTROL_PORT}/healthz" ]
#      interval: 10s
#      timeout: 20s
#      retries: 3

  tts:
    image: freechatfun/freechat-tts:${TTS_TAG}
    ports:
      - ${TTS_HOST_PORT}:${TTS_PORT}
    container_name: ${TTS_NAME}
    volumes:
      - ${TTS_VOLUME}:/root/data
    environment:
      - DATA_HOME=/root/data
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:${TTS_PORT}/ping"]
      interval: 10s
      timeout: 20s
      retries: 3
